### ISSUE TITLE
Skipping the -g argument on a non-single name game.

### ISSUE THREAD

**Issue by StuffonGithub** [JosephCantrell/Auto-Twitch-Drops#2]
Hi again! Sorry if i keep on opening dumb issues.

Since I got it to work now, I'm testing the script on Rainbow6 games but for some reason, it's skipping the streamers who are actually streaming the game I'm looking for.

I've ran these so far with the same results:

`python3 autotwitch.py -g rainbow6`

`python3 autotwitch.py -g "Tom Clancy's Rainbow Six Siege"`

`python3 autotwitch.py -g "Tom Clancys Rainbow Six Siege"`

`python3 autotwitch.py -g "TomClancy'sRainbowSixSiege"`

`python3 autotwitch.py -g "TomClancysRainbowSixSiege"`

`python3 autotwitch.py -g "Tom%20Clancy's%20Rainbow%20Six%20Siege"`

`python3 autotwitch.py -g "Tom%20Clancys%20Rainbow%20Six%20Siege"`

What should be the proper formatting for the -g argument if it contains several words? Sorry for yet another dumb question.

**Comment by JosephCantrell** [comment]
Sorry about not responding. I am currently looking into this. I actually didn't get to test this code before uploading it due to time restrictions. Ive been using it for the rust stream drops. Ive got it working on single named games. Let me look into this more.

**Comment by JosephCantrell** [comment]
Hey, I tested and found the bug. During game name comparison the user input game was being cast lower, while the stream game name was not, causing the bot to think the games were different. This has to be performed in case of Users when starting the bot doesn't properly capitalize the game name. you would call Rainbow Six as -g "Tom Clancy's Rainbow Six Siege". I added a time parameter that allows for the default 120-minute override due to twitch drops not always taking 2 hours. This should fix your issue. It was fully working on my end

**Comment by StuffonGithub** [comment]
@JosephCantrell Thanks so much for the quick resolution! I can confirm it's working on mine now as well. :)

I have a couple follow up though if that's not a problem.

1. For the new time parameter, is there an option to make it indefinite or "999999999" is just fine? Lol. I'm planning to make it watch for, at least, the next full 48 hours due to a timed drop event.

2. Speaking of the above, is there a way to make the script reset back to the top of the streamer's list once it reaches the last one listed? Or will if be fine if I just copy paste all the streamer links in my config.py multiple times?

Thanks again for this btw! This script is exactly what I was looking for.  The rest I've found are too complicated, outdated, or much more difficult to run.

**Comment by JosephCantrell** [comment]
Just pushed a new update for you. -t now if left unstated will cause the bot to watch a stream endlessly. -l will override the drop boolean to loop through the streamers after the -t time (doesn't work if you leave it to watch a stream endlessly). The stream will move on if the streamer stops streaming or streaming the game you want to watch.

Essentially with a call like this "easyapplybot.py -g "Tom Clancy's Rainbow Six Siege" -l" will cause it to loop through the streamers when it reaches the end, and watch forever

**Comment by StuffonGithub** [comment]
Thank you so much for a quick and specialised support! :)
